{
 "title": "Keycloak Metrics Dashboard",
 "description": "Dashboard of Keycloak metrics exported with Keycloak Metrics SPI\r\n\r\nhttps://github.com/aerogear/keycloak-metrics-spi",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(keycloak_logins,kubernetes_pod_name)"
    }
   },
   {
    "name": "realm",
    "label": "Realm",
    "query": {
     "query": "label_values(keycloak_logins{provider=\"keycloak\"},realm)"
    }
   },
   {
    "name": "ClientId",
    "label": "ClientId",
    "query": {
     "query": "label_values(keycloak_logins{provider=\"keycloak\",realm=\"$realm\"},client_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current Memory HEAP",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(jvm_memory_bytes_used{kubernetes_pod_name=\"$instance\", area=\"heap\"})/sum(jvm_memory_bytes_max{kubernetes_pod_name=\"$instance\", area=\"heap\"}))*100"
    }
   ]
  },
  {
   "title": "Current Memory nonHEAP",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(jvm_memory_bytes_used{kubernetes_pod_name=\"$instance\", area=\"nonheap\"})/sum(jvm_memory_bytes_max{kubernetes_pod_name=\"$instance\", area=\"nonheap\"}))*100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_max{kubernetes_pod_name=\"$instance\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{kubernetes_pod_name=\"$instance\"})",
     "legendFormat": "Comitted"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{kubernetes_pod_name=\"$instance\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(jvm_memory_bytes_init{kubernetes_pod_name=\"$instance\"})",
     "legendFormat": "Init"
    }
   ]
  },
  {
   "title": "Logins Per REALM for past 24h",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (realm) (keycloak_logins_total{kubernetes_pod_name=\"$instance\"})",
     "legendFormat": "{{realm}}"
    }
   ]
  },
  {
   "title": "Registrations Per REALM for past 24h",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (realm) (keycloak_admin_event_CREATE_total{kubernetes_pod_name=\"$instance\", resource=\"USER\"})",
     "legendFormat": "{{ $realm }}"
    }
   ]
  },
  {
   "title": "Logins Per CLIENT for past 24h",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (client_id)(keycloak_logins_total{kubernetes_pod_name=\"$instance\"})",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Deletions Per Realm for past 24h",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (realm) (keycloak_admin_event_DELETE_total{kubernetes_pod_name=\"$instance\", resource=\"USER\"})",
     "legendFormat": "{{ $realm }}"
    }
   ]
  },
  {
   "title": "Logins per REALM",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (realm) (keycloak_logins_total{kubernetes_pod_name=\"$instance\"})",
     "legendFormat": "{{ $realm }}"
    }
   ]
  },
  {
   "title": "Logins per CLIENT on realm $realm",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (client_id) (keycloak_logins_total)",
     "legendFormat": "{{ $client_id }}"
    }
   ]
  },
  {
   "title": "Login Errors per REALM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (realm) (keycloak_failed_login_attempts_total{kubernetes_pod_name=\"$instance\"})",
     "legendFormat": "{{ $realm }}"
    }
   ]
  },
  {
   "title": "Registrations per REALM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (realm) (keycloak_admin_event_CREATE_total{kubernetes_pod_name=\"$instance\", resource=\"USER\"})",
     "legendFormat": "{{ $realm }}"
    }
   ]
  },
  {
   "title": "Total Update Actions on realms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (realm) (keycloak_admin_event_UPDATE_total{kubernetes_pod_name=\"$instance\"})",
     "legendFormat": "{{ $realm }}"
    }
   ]
  },
  {
   "title": "4xx and 5xx Error Responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (code)(keycloak_response_errors_total)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Request duration method = \"GET\" Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum(increase(keycloak_request_duration_bucket{method=\"GET\"}[30m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Percentage of requests \"GET\"  method  was served in 100ms or below",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(keycloak_request_duration_bucket{method=\"GET\", le=\"100.0\"}[30m])) / sum(rate(keycloak_request_duration_count{method=\"GET\"}[30m])) * 100"
    }
   ]
  },
  {
   "title": "Request duration method = \"POST\" Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum(increase(keycloak_request_duration_bucket{method=\"POST\"}[30m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Percentage of requests \"POST\"  method  was served in 100ms or below",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(keycloak_request_duration_bucket{method=\"POST\", le=\"100.0\"}[30m])) / sum(rate(keycloak_request_duration_count{method=\"POST\"}[30m])) * 100"
    }
   ]
  }
 ]
}