{
 "title": "Kubernetes Cluster Monitoring",
 "description": "https://em8g.com - free kubernetes monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "{\"find\": \"terms\", \"field\": \"agent.hostname\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": "2" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "agent.hostname", "id": "4", "type": "cardinality" }
     ],
     "query": "event.dataset:kubernetes.node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total Cores",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "5", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "2" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "system.cpu.cores", "id": "4", "type": "sum" }
     ],
     "query": "event.dataset:system.cpu",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "5", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "2" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "system.memory.total", "id": "4", "type": "sum" }
     ],
     "query": "event.dataset:system.memory",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total File System Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "5", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "2" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "kubernetes.node.fs.capacity.bytes",
       "id": "4",
       "type": "sum"
      }
     ],
     "query": "event.dataset:kubernetes.node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Cluster Events",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "event.dataset:kubernetes.event",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": "2" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "kubernetes.pod.name", "id": "4", "type": "cardinality" }
     ],
     "query": "event.dataset:kubernetes.pod",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "5", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "2" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "system.cpu.total.norm.pct", "id": "4", "type": "avg" }
     ],
     "query": "event.dataset:system.cpu",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "5", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "2" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "system.memory.actual.used.pct", "id": "4", "type": "avg" }
     ],
     "query": "event.dataset:system.memory",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "File System Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "5", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "2" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "kubernetes.node.fs.used.bytes",
       "hide": true,
       "id": "4",
       "type": "sum"
      },
      {
       "field": "kubernetes.node.fs.capacity.bytes",
       "hide": true,
       "id": "6",
       "type": "sum"
      },
      {
       "id": "7",
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "4" },
        { "name": "var2", "pipelineAgg": "6" }
       ],
       "settings": { "script": "params.var1 / params.var2" },
       "type": "bucket_script"
      }
     ],
     "query": "event.dataset:kubernetes.node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Cluster CPU Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "Usage %",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": "2" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "system.cpu.total.norm.pct", "id": "1", "type": "avg" }
     ],
     "query": "event.dataset:system.cpu",
     "timeField": "@timestamp"
    },
    {
     "alias": "Usage Nanocores",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": "2" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "kubernetes.node.cpu.usage.nanocores",
       "id": "1",
       "type": "sum"
      }
     ],
     "query": "event.dataset:kubernetes.node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "Usage %",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": "2" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "system.memory.actual.used.pct", "id": "1", "type": "avg" }
     ],
     "query": "event.dataset:system.memory",
     "timeField": "@timestamp"
    },
    {
     "alias": "Usage Bytes",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": "2" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.memory.actual.used.bytes",
       "id": "1",
       "type": "sum"
      }
     ],
     "query": "event.dataset:system.memory",
     "timeField": "@timestamp"
    },
    {
     "alias": "Available Bytes",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": "2" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.memory.actual.free",
       "hide": false,
       "id": "1",
       "type": "sum"
      }
     ],
     "query": "event.dataset:system.memory",
     "timeField": "@timestamp"
    },
    {
     "alias": "Capacity Bytes",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": "2" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.memory.total",
       "hide": false,
       "id": "1",
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event.dataset:system.memory",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Cluster File System Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "Usage %",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": "2" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "kubernetes.node.fs.used.bytes",
       "hide": true,
       "id": "1",
       "type": "sum"
      },
      {
       "field": "kubernetes.node.fs.capacity.bytes",
       "hide": true,
       "id": "3",
       "type": "sum"
      },
      {
       "id": "4",
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "1" },
        { "name": "var2", "pipelineAgg": "3" }
       ],
       "settings": { "script": "params.var1 / params.var2" },
       "type": "bucket_script"
      }
     ],
     "query": "event.dataset:kubernetes.node",
     "timeField": "@timestamp"
    },
    {
     "alias": "Usage Bytes",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": "2" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "kubernetes.node.fs.used.bytes",
       "hide": false,
       "id": "1",
       "type": "sum"
      }
     ],
     "query": "event.dataset:kubernetes.node",
     "timeField": "@timestamp"
    },
    {
     "alias": "Available Bytes",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": "2" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "kubernetes.node.fs.available.bytes",
       "hide": false,
       "id": "4",
       "type": "sum"
      }
     ],
     "query": "event.dataset:kubernetes.node",
     "timeField": "@timestamp"
    },
    {
     "alias": "Capacity Bytes",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": "2" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "kubernetes.node.fs.capacity.bytes",
       "hide": false,
       "id": "4",
       "type": "sum"
      }
     ],
     "query": "event.dataset:kubernetes.node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Cluster Network Traffic",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "alias": "in (rx)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": "2" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "kubernetes.node.network.rx.bytes",
       "hide": false,
       "id": "1",
       "settings": {
        "script": "_value  / $__interval_ms * 1000"
       },
       "type": "sum"
      }
     ],
     "query": "event.dataset:kubernetes.node",
     "timeField": "@timestamp"
    },
    {
     "alias": "out (tx)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": "2" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "kubernetes.node.network.tx.bytes",
       "hide": false,
       "id": "1",
       "settings": {
        "script": "-_value  / $__interval_ms * 1000"
       },
       "type": "sum"
      }
     ],
     "query": "event.dataset:kubernetes.node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Node CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "agent.hostname",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": "2" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "kubernetes.node.cpu.total.norm.pct",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "agent.hostname:$node AND event.dataset:kubernetes.node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Node File System Usage",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "agent.hostname",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": "2" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "kubernetes.node.fs.used.bytes",
       "hide": true,
       "id": "1",
       "type": "avg"
      },
      {
       "field": "kubernetes.node.fs.capacity.bytes",
       "hide": true,
       "id": "4",
       "type": "avg"
      },
      {
       "id": "5",
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "1" },
        { "name": "var2", "pipelineAgg": "4" }
       ],
       "settings": { "script": "params.var1 / params.var2" },
       "type": "bucket_script"
      }
     ],
     "query": "agent.hostname:$node AND event.dataset:kubernetes.node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Node Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "agent.hostname",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": "2" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "kubernetes.node.memory.actual.used.pct",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "agent.hostname:$node AND event.dataset:kubernetes.node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Node Network Traffic",
   "type": "bargauge",
   "description": "In(rx) + Out(tx)",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "agent.hostname",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": "2" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "kubernetes.node.network.rx.bytes",
       "hide": true,
       "id": "1",
       "type": "sum"
      },
      {
       "field": "1",
       "hide": true,
       "id": "4",
       "pipelineAgg": "1",
       "type": "derivative"
      },
      {
       "field": "kubernetes.node.network.tx.bytes",
       "hide": true,
       "id": "5",
       "type": "sum"
      },
      {
       "field": "5",
       "hide": true,
       "id": "6",
       "pipelineAgg": "5",
       "type": "derivative"
      },
      {
       "id": "7",
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "4" },
        { "name": "var2", "pipelineAgg": "6" }
       ],
       "settings": {
        "script": "(params.var1 + params.var2) / $__interval_ms * 1000"
       },
       "type": "bucket_script"
      }
     ],
     "query": "agent.hostname:$node AND event.dataset:kubernetes.node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Node - Pod Allocation",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "agent.hostname",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "100" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "6", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "2" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "kubernetes.pod.name", "id": "1", "type": "cardinality" }
     ],
     "query": "agent.hostname:$node AND event.dataset:kubernetes.pod",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Pod CPU Usage",
   "type": "bargauge",
   "description": "CPU usage as a percentage of the defined limit for the pod containers (or total node CPU if one or more containers of the pod are unlimited)",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "kubernetes.pod.name",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0", "trimEdges": "2" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "kubernetes.pod.cpu.usage.limit.pct",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "agent.hostname:$node AND event.dataset:kubernetes.pod",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "bargauge",
   "description": "Memory usage as a percentage of the defined limit for the pod containers (or total node allocatable memory if unlimited)",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "kubernetes.pod.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": "2" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "kubernetes.pod.memory.usage.limit.pct",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "agent.hostname:$node AND event.dataset:kubernetes.pod",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Pod Network Traffic",
   "type": "bargauge",
   "description": "In(rx) + Out(tx)",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "kubernetes.pod.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": "2" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "kubernetes.pod.network.rx.incBytes",
       "hide": true,
       "id": "1",
       "type": "sum"
      },
      {
       "field": "kubernetes.pod.network.tx.incBytes",
       "hide": true,
       "id": "4",
       "type": "sum"
      },
      {
       "hide": false,
       "id": "5",
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "1" },
        { "name": "var2", "pipelineAgg": "4" }
       ],
       "settings": {
        "script": "(params.var1 + params.var2) / $__interval_ms * 1000"
       },
       "type": "bucket_script"
      }
     ],
     "query": "agent.hostname:$node AND event.dataset:kubernetes.pod",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}